import SideBar from "@/components/SideBar";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const inter = Inter({ subsets: ["latin"] });
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div className={inter.className}>
      <main className="m-auto flex h-[100vh] w-full bg-primary p-4">
        <div className="">
          <SideBar />
        </div>

        <div className="ml-2"> {children}</div>
      </main>
    </div>
  );
}
